# title: Natasha Toghramadjian
# baseurl: "/researcher"

markdown: kramdown
# ins_logo: "ararat.png"

tracking_id: #

footer: yes
# footer_url: "https://github.com/ntoghrama"
# footer_text: "Link to Github"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Seattle Experiment"
   link: "/Seattle/"
 - name: "CV"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"