# title: Natasha Toghramadjian
# baseurl: "/researcher"

markdown: kramdown
# ins_logo: "ararat.png"

tracking_id: #

footer: yes
# footer_url: "https://github.com/ntoghrama"
# footer_text: "Link to Github"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About "
   link: "/researcher/"
 - name: "Seattle Experiment "
   link: "/Seattle /"
 - name: "Armenia "
   link: "/Hayastan /"
 - name: "CV "
   link: "resume.pdf"
 - name: "Educational Outreach"
   link: "poster_Get_to_know_our_seismic_station.pdf"
   link: "poster_Jesuit_seis.pdf"
 - name: "Contact"
   link: "contact"